apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidlingo-test
  namespace: vidlingo
  labels:
    app: vidlingo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: vidlingo
  template:
    metadata:
      labels:
        app: vidlingo
    spec:
      containers:
      - name: web-test
        image: nginx:alpine
        ports:
        - containerPort: 80
